# Generated by Django 4.2.29 on 2026-03-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, verbose_name='Марка погрузчика')),
                ('number', models.CharField(max_length=100, verbose_name='Номер погрузчика')),
                ('capacity', models.DecimalField(decimal_places=3, help_text='Максимальная точность 3 знака после запятой', max_digits=10, verbose_name='Грузоподъемность')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Погрузчик',
                'verbose_name_plural': 'Погрузчики',
                'ordering': ['-created_at'],
            },
        ),
    ]
