# Generated by Django 4.2.29 on 2026-03-22 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loader', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loader',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Погрузчик', 'verbose_name_plural': 'Погрузчики'},
        ),
        migrations.AddField(
            model_name='loader',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Код записи'),
        ),
        migrations.AddField(
            model_name='loader',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='loader',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='loader',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='loader',
            name='capacity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Грузоподъемность'),
        ),
        migrations.AlterField(
            model_name='loader',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='loader',
            name='number',
            field=models.CharField(max_length=100, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='loader',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Начало')),
                ('end_time', models.DateTimeField(verbose_name='Окончание')),
                ('duration', models.CharField(max_length=50, verbose_name='Время простоя')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('loader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtimes', to='loader.loader', verbose_name='Погрузчик')),
            ],
            options={
                'verbose_name': 'Простой',
                'verbose_name_plural': 'Простои',
                'ordering': ['-start_time'],
            },
        ),
    ]
